<?php
/**
 * hook_block_info
 * 
 * hooki asemel enda mooduli nimi
 */ 

function front_page_products_block_info() { 

  // This example comes from node.module.
  $blocks['fpp_block'] = array(
    'info' => t('Esilehele väljatoodud tooted'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

function fpp_block_view($delta = '') {

  // This example is adapted from node.module.
  $block = array();
  switch ($delta) {
    case 'fpp_block':
      $block['subject'] = t('');
      $block['content'] = fpp_get_products();
      break;
    
  }
  return $block;
}
function fpp_get_products(){
    
    $query = db_select('node','n'); 
    $query -> condition('n.type','product','='); 
    $query -> condition('n.status',1,'=');
    $query -> fields('n'); 
    $results = $query->execute(); 
    $toode = ''; 
    while($product = $results->fetchAssoc()){
        
        $node = node_load($product['nid']);
        $toode.='<div class="col-sm-4">';
        $toode.='<div class="thumbnail product-front">';
        $image_url='';
        if(!empty($node->uc_product_image)){        
          $image = $node->uc_product_image['und'][0]; 
          $image_url = image_style_url('medium',$image['uri']);
        }
        $toode.='<div class="product-name">';
        $toode.= 'Toote nimi: '.$node->title; 
        $toode.='</div>';
    
        if(!empty($image_url)){
          $toode.= '<img src="'.$image_url.'"></img>';
        }
        if(!empty($node->body)) {
          $text = $node->body['und'][0]['value'];
          $text=substr($text,0,200);
          $toode.=$text;
        }
        $toode .= ' Toote hind:'.number_format($node->sell_price,2) . '$';
        $toode.='<div class="read-more">';
        $toode.= '<a class="btn btn-default" href="'.url('node/'.$node->nid).'">'.'Vaata lähemalt'.'</a>';
        $toode.='</div>';
        $toode.='</div>';
        $toode.='</div>';
        //krumo($node);
    }
    $output= '<div class="container">
                <div class="row">
                  '.$toode.'
                </div>
              </div>';
    return $output;
}